name: Agent Service CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'apps/agent-service/**'
      - '.github/workflows/agent-service.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'apps/agent-service/**'

jobs:
  build-and-lint:
    name: Build & Lint Agent Service
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/agent-service/package-lock.json

      - name: Install dependencies
        working-directory: apps/agent-service
        run: npm ci

      - name: TypeScript compilation
        working-directory: apps/agent-service
        run: npm run build

      - name: Lint TypeScript
        working-directory: apps/agent-service
        run: npm run lint
        continue-on-error: true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: agent-service-dist
          path: apps/agent-service/dist
          retention-days: 7

  test:
    name: Test Agent Service
    runs-on: ubuntu-latest
    needs: build-and-lint
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/agent-service/package-lock.json

      - name: Install dependencies
        working-directory: apps/agent-service
        run: npm ci

      - name: Run tests
        working-directory: apps/agent-service
        run: npm test
        continue-on-error: true
