name: Smart Contracts CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'packages/contracts/**'
      - '.github/workflows/contracts.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'packages/contracts/**'

jobs:
  test:
    name: Compile & Test Contracts
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: packages/contracts/package-lock.json

      - name: Install dependencies
        working-directory: packages/contracts
        run: npm ci

      - name: Compile contracts
        working-directory: packages/contracts
        run: npm run build

      - name: Run tests
        working-directory: packages/contracts
        run: npm test

      - name: Run Solhint
        working-directory: packages/contracts
        run: npm run lint
        continue-on-error: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: contract-artifacts
          path: |
            packages/contracts/artifacts
            packages/contracts/typechain-types
          retention-days: 7

  gas-report:
    name: Gas Usage Report
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: packages/contracts/package-lock.json

      - name: Install dependencies
        working-directory: packages/contracts
        run: npm ci

      - name: Generate gas report
        working-directory: packages/contracts
        run: REPORT_GAS=true npm test

      - name: Comment PR with gas report
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const gasReport = '⛽ Gas usage report will be available when hardhat-gas-reporter is configured';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: gasReport
            });
